version: "3.7"
services:
  web:
    build:
      target: dev
    image:
      name_generator:dev
    ports:
      - "80:3000"
    volumes:
      - ./app/src:/usr/src/app/src
      - ./app/NodeServer:/usr/src/app/NodeServer
